### ISSUE TITLE
Clicking on Setting Icon Doesn't Close the Setting Menu

### ISSUE THREAD

**Issue by iamanishsrivastava** [iamanishsrivastava/MediCare#22]
### Description
When clicking on the settings icon, the setting menu should toggle its visibility. However, currently, clicking on the icon only opens the menu, and it does not close when the icon is clicked again.

### Steps to Reproduce
1. Open the application.
2. Click on the settings icon to open the setting menu.
3. Click on the settings icon again to close the setting menu.

### Expected Behavior
Clicking on the settings icon should toggle the visibility of the setting menu. If the menu is already open, clicking on the icon again should close it.

### Actual Behavior
Clicking on the settings icon only opens the menu, but it does not close the menu when clicked again.

### Possible Solution
Inspect the event handling function for the settings icon click event. Ensure that it properly toggles the visibility of the setting menu by checking its current state and toggling it accordingly.

### Screenshots
![image](https://github.com/iamanishsrivastava/MediCare/assets/83644811/ea22b952-707c-429d-a7ed-64acf29b9a69)

### Suggestion
Please make sure that you are in the correct directory where the `package.json` file is located. You'll need to navigate to the "medicare-proj" directory, as that's where the `package.json` file is present.

Once you're in the `medicare-proj` directory, you can install the project dependencies by running `npm install`. After that, you can try running the project with the appropriate command (`npm start`, `npm run dev`, etc.).

**Comment by razouq** [comment]
Can you assign this ticket to me

**Comment by pdeep1506** [comment]
ENOENT: no such file or directory, open '/Users/deeppatel/Desktop/open_source/MediCare/package.json'

**Comment by iamanishsrivastava** [comment]
> Can you assign this ticket to me

assigned

**Comment by iamanishsrivastava** [comment]
> ENOENT: no such file or directory, open '/Users/deeppatel/Desktop/MediCare/package.json'

It seems like there might be a misunderstanding or confusion. The issue I posted is related to the functionality of the settings icon and menu in the application, while your comment mentions a missing package.json file in a specific directory.

**Comment by pdeep1506** [comment]
its give me error, when I am trying to run project

**Comment by iamanishsrivastava** [comment]
> its give me error, when I am trying to run project

It seems like you're encountering an error when trying to run the project due to a missing `package.json` file. This file is essential for managing project dependencies and scripts.

To resolve this issue, please make sure that you are in the correct directory where the `package.json` file is located. You'll need to navigate to the "medicare-proj" directory, as that's where the `package.json` file is present.

Once you're in the `medicare-proj` directory, you can install the project dependencies by running `npm install`. After that, you can try running the project again with the appropriate command (`npm start`, `npm run dev`, etc.).

For further information, you can check out the [Contributing Guide](https://github.com/iamanishsrivastava/MediCare/blob/main/contributing.md) provided by the MediCare Team.
